import { useState, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAppDispatch } from '../store';
import { query, createPage, createShareLink } from '../api';
import type { Page } from '../types';
import { renderMarkdown } from '../pages/markdown';
import { Button } from './ui/Button';
import { Card } from './ui/Card';
import { Textarea } from './ui/Textarea';
import { useToast } from './ui/Toast';

export default function QueryPanel() {
  const dispatch = useAppDispatch();
  const navigate = useNavigate();
  const { push } = useToast();
  const [question, setQuestion] = useState('');
  const [answer, setAnswer] = useState('');
  const [citations, setCitations] = useState<Page[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [sharing, setSharing] = useState(false);
  const [savedSlug, setSavedSlug] = useState<string | null>(null);
  const [shareUrl, setShareUrl] = useState<string | null>(null);
  const answerRef = useRef('');

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!question.trim() || loading) return;

    setAnswer('');
    setCitations([]);
    setError(null);
    setSavedSlug(null);
    setShareUrl(null);
    answerRef.current = '';
    setLoading(true);

    try {
      await query(
        question.trim(),
        (token) => {
          answerRef.current += token;
          setAnswer(answerRef.current);
        },
        (pages) => {
          setCitations(pages);
        },
      );
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setLoading(false);
    }
  }

  async function handleSaveAsPage() {
    if (!answer || saving) return;
    setSaving(true);
    try {
      const titleLine = question.trim().slice(0, 80);
      const content = `# ${titleLine}\n\n> *Generated by Archivum AI*\n\n${answer}\n\n---\n\n**Sources:**\n${citations.map((c) => `- [[${c.slug}|${c.title}]]`).join('\n')}`;

      const page = await createPage({ title: titleLine, content });
      dispatch({ type: 'UPSERT_PAGE', page });
      setSavedSlug(page.slug);
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setSaving(false);
    }
  }

  async function handleShareQuery() {
    if (!answer || sharing) return;
    if (shareUrl) {
      await navigator.clipboard.writeText(shareUrl);
      push({ kind: 'success', title: 'Copied', description: 'Query permalink copied to clipboard' });
      return;
    }

    setSharing(true);
    try {
      const result = await createShareLink({
        type: 'query',
        question: question.trim(),
        answer,
        citations: citations.map((c) => ({ slug: c.slug, title: c.title })),
      });
      const fullUrl = window.location.origin + result.url;
      setShareUrl(fullUrl);
      await navigator.clipboard.writeText(fullUrl);
      push({ kind: 'success', title: 'Copied', description: 'Query permalink copied to clipboard' });
    } catch (err) {
      const message = (err as Error).message;
      setError(message);
      push({ kind: 'error', title: 'Share failed', description: message });
    } finally {
      setSharing(false);
    }
  }

  return (
    <div className="flex h-full w-full flex-col bg-transparent">
      {/* Input area */}
      <div
        className="subtle-divider shrink-0 border-b bg-white/[0.02] p-4 backdrop-blur"
      >
        <h2 className="text-sm font-semibold text-muted-foreground mb-3 uppercase tracking-wider">
          Ask Archivum
        </h2>
        <form onSubmit={handleSubmit} className="flex gap-2">
          <Textarea
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            placeholder="Ask a question about your notes..."
            rows={3}
            onKeyDown={(e) => {
              if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) {
                e.preventDefault();
                handleSubmit(e);
              }
            }}
            className="flex-1 resize-none min-h-[88px]"
          />
          <Button
            type="submit"
            variant="primary"
            disabled={loading || !question.trim()}
            className="self-end"
          >
            {loading ? 'Querying...' : 'Ask'}
          </Button>
        </form>
        <p className="text-xs text-muted-foreground mt-1">Ctrl+Enter to submit</p>
      </div>

      {/* Answer area */}
      <div className="flex-1 overflow-y-auto p-4">
        {error && (
          <div className="rounded-lg p-3 mb-4 text-sm text-red-300 border border-red-400/25 bg-red-500/10">
            {error}
          </div>
        )}

        {loading && !answer && (
          <div className="space-y-2">
            <div className="skeleton h-4 w-full" />
            <div className="skeleton h-4 w-5/6" />
            <div className="skeleton h-4 w-4/5" />
          </div>
        )}

        {answer && (
          <div className="w-full">
            {/* Streaming indicator */}
            {loading && (
              <div className="flex items-center gap-2 mb-3">
                <span className="inline-block w-2 h-2 rounded-full bg-accent animate-pulse" />
                <span className="text-xs text-muted-foreground">Generating...</span>
              </div>
            )}

            {/* Answer content */}
            <div
              className="md-body"
              dangerouslySetInnerHTML={{ __html: renderMarkdown(answer) }}
            />

            {/* Actions */}
            {!loading && (
              <div className="subtle-divider mt-6 flex items-center gap-3 border-t pt-4">
                {savedSlug ? (
                  <button
                    onClick={() => navigate(`/wiki/${savedSlug}`)}
                    className="text-sm text-accent hover:underline"
                  >
                    View saved page →
                  </button>
                ) : (
                  <Button
                    onClick={handleSaveAsPage}
                    disabled={saving}
                    variant="secondary"
                    size="sm"
                  >
                    {saving ? 'Saving...' : 'Save as page'}
                  </Button>
                )}
                <Button
                  onClick={handleShareQuery}
                  disabled={sharing}
                  variant="secondary"
                  size="sm"
                >
                  {sharing ? 'Sharing...' : shareUrl ? 'Copy link' : 'Share result'}
                </Button>
              </div>
            )}

            {/* Citations */}
            {citations.length > 0 && (
              <div
                className="subtle-divider mt-6 border-t pt-4"
              >
                <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-3">
                  Sources
                </h3>
                <div className="space-y-1">
                  {citations.map((page) => (
                    <button
                      key={page.slug}
                      onClick={() => navigate(`/wiki/${page.slug}`)}
                      className="block text-left w-full text-sm text-accent hover:underline"
                    >
                      {page.title}
                    </button>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

        {!loading && !answer && !error && (
          <div className="flex items-center justify-center h-full">
            <Card className="max-w-sm p-4">
              <p className="text-muted-foreground text-sm">
                Ask a question and Archivum will answer from your notes with linked sources.
              </p>
            </Card>
          </div>
        )}
      </div>
    </div>
  );
}
